build: false

environment:
    PYTHON_HOME: "C:\\Python37"
    CONAN_TRACE_FILE: "%TEMP%\\conan-trace.log"
    CONAN_VERBOSE_TRACEBACK: 1

    matrix:
        - MINGW_CONFIGURATIONS: '4.9@x86_64@seh@posix'
          CONAN_BASH_PATH: "c:\\msys64\\usr\\bin\\bash"
        - MINGW_CONFIGURATIONS: '5@x86_64@seh@posix'
          CONAN_BASH_PATH: "c:\\msys64\\usr\\bin\\bash"
        - MINGW_CONFIGURATIONS: '6@x86_64@seh@posix'
          CONAN_BASH_PATH: "c:\\msys64\\usr\\bin\\bash"
        - MINGW_CONFIGURATIONS: '7@x86_64@seh@posix'
          CONAN_BASH_PATH: "c:\\msys64\\usr\\bin\\bash"

install:
  - set PATH=%PYTHON_HOME%;%PYTHON_HOME%/Scripts/;%PATH%
  - pip.exe install conan --upgrade
  - pip.exe install conan_package_tools bincrafters_package_tools
  - conan user # It creates the conan data directory

test_script:
  - curl -v "https://api.bintray.com/conan/conan/conan-center/v1/files/conan/mingw_installer/1.0/stable/0/package/da79baa1f392d5cc5d0d05b5af3ef152fe9281e2/0/conanmanifest.txt"
  - python build.py || true
  - type "%TEMP%\\conan-trace.log"
